apiVersion: devops.kubesphere.io/v1alpha3
kind: ClusterStepTemplate
metadata:
  name: error
  labels:
    step.devops.kubesphere.io/category: "General"
  annotations:
    devops.kubesphere.io/displayNameZH: "异常退出"
    devops.kubesphere.io/descriptionZH: "错误信号，异常退出流水线"
    devops.kubesphere.io/displayNameEN: "Exit With Error"
    devops.kubesphere.io/descriptionEN: "Signals an error, exit the Pipeline and mark it as failed"
    step.devops.kubesphere.io/icon: "clock"
spec:
  runtime: dsl
  parameters:
    - name: message
      type: string
      display: 'Error Message'
  template: |
    {
      "arguments": [
        {
          "key": "message",
          "value": {
            "isLiteral": true,
            "value": "{{.param.message}}"
          }
        }
      ],
      "name": "error"
    }
