apiVersion: devops.kubesphere.io/v1alpha3
kind: ClusterStepTemplate
metadata:
  name: checkout
  labels:
    step.devops.kubesphere.io/category: "scm"
  annotations:
    devops.kubesphere.io/displayNameZH: "SVN Clone"
    devops.kubesphere.io/descriptionZH: "拉取SVN仓库的代码"
    devops.kubesphere.io/displayNameEN: "SVN Clone"
    devops.kubesphere.io/descriptionEN: "Pull code from the SVN-Repo"
spec:
  runtime: dsl
  parameters:
    - name: remote
      type: string
      display: 'SVN URL'
    - name: credentialsId
      type: secret
      display: 'Secret'
  template: |
    {
      "arguments": [
        {
          "key": "scm",
          "value": {
            "isLiteral": false,
            "value": "[$class: 'SubversionSCM', locations: [[cancelProcessOnExternalsFail: true,  credentialsId: '{{.param.credentialsId.name}}', depthOption: 'infinity', ignoreExternalsOption: true, local: '.', remote: '{{.param.remote}}']], quietOperation: true, workspaceUpdater: [$class: 'UpdateUpdater']]"
          }
        },
        {
          "key": "poll",
          "value": {
            "isLiteral": true,
            "value": false
          }
        }
      ],
      "name": "checkout"
    }
