apiVersion: devops.kubesphere.io/v1alpha3
kind: ClusterStepTemplate
metadata:
  name: waitforqualitygate
  labels:
    step.devops.kubesphere.io/category: "Review"
  annotations:
    devops.kubesphere.io/descriptionZH: "代码质量检查"
    devops.kubesphere.io/displayNameZH: "运行代码质量检查（SonarQube）"
    devops.kubesphere.io/descriptionEN: "Execute code analysis(SonarQube)"
    devops.kubesphere.io/displayNameEN: "WaitForQualityGate"
    step.devops.kubesphere.io/icon: "terminal"
    step.devops.kubesphere.io/tip: "Code quality check standards are derived from SonarQube's Quality Gate. If you need to customize the standards, go to SonarQube settings."
spec:
  runtime: dsl
  parameters:
    - name: abortPipeline
      type: bool
      display: "AbortPipeline if quality gate status is not green"
      defaultValue: "false"
  template: |
    {
      "arguments": [
        {
          "key": "abortPipeline",
          "value": {
            "isLiteral": true,
            "value": "{{.param.abortPipeline}}"
          }
        }
      ],
      "name": "waitForQualityGate"
    }
