apiVersion: devops.kubesphere.io/v1alpha3
kind: ClusterStepTemplate
metadata:
  name: withsonarqubeenv
  labels:
    step.devops.kubesphere.io/category: "Review"
  annotations:
    devops.kubesphere.io/descriptionZH: "加载附带 SonarQube 配置的代码块（在其中运行代码检查））"
    devops.kubesphere.io/displayNameZH: "SonarQube 配置"
    devops.kubesphere.io/descriptionEN: "Load a code block with sonarqube configuration environments(run code-review in it)"
    devops.kubesphere.io/displayNameEN: "WithSonarQubeEnv"
    step.devops.kubesphere.io/icon: "terminal"
spec:
  runtime: dsl
  parameters:
    - name: config
      type: string
      display: 'Config Name'
      required: true
  template: |
    {
      "arguments": {
        "isLiteral": true,
        "value": "{{.param.config}}"
      },
      "children": [],
      "name": "withSonarQubeEnv"
    }
