apiVersion: devops.kubesphere.io/v1alpha3
kind: ClusterStepTemplate
metadata:
  name: withcredentials
  labels:
    step.devops.kubesphere.io/category: "general"
  annotations:
    devops.kubesphere.io/displayNameEN: "Load credential"
    devops.kubesphere.io/descriptionEN: "Loading credential into the environment variables"
    step.devops.kubesphere.io/icon: "key"
spec:
  runtime: dsl
  parameters:
    - name: credentialsId
      type: secret
      display: 'Credential Name'
    - name: usernameVariable
      type: string
      display: 'Username Variable'
      defaultValue: 'USER'
    - name: passwordVariable
      type: string
      display: 'Password Variable'
      defaultValue: 'PASSWD'
  template: |
    {
      "arguments": {
        "isLiteral": false,
        "value": "${[usernamePassword(credentialsId: '{{.param.credentialsId}}', passwordVariable: '{{.param.passwordVariable}}', usernameVariable: '{{.param.usernameVariable}}')]}"
      },
      "children": [],
      "name": "withCredentials"
    }
